#!/bin/bash

RUN_DIR=/var/vcap/sys/run/altman-syslog
LOG_DIR=/var/vcap/sys/log/altman-syslog

PIDFILE=$RUN_DIR/altman-syslog.pid
RUNAS=vcap

export PATH=/var/vcap/packages/node/bin:$PATH

function pid_exists() {
  ps -p $1 &> /dev/null
}

case $1 in

  start)
    mkdir -p $RUN_DIR $LOG_DIR
    chown -R $RUNAS:$RUNAS $RUN_DIR $LOG_DIR

    echo $$ > $PIDFILE

    exec chpst -u $RUNAS:$RUNAS \
      node /var/vcap/packages/altman-syslog/altman-syslog.js /var/vcap/jobs/altman-syslog/config/config.json \
      >>$LOG_DIR/altman-syslog.stdout.log 2>>$LOG_DIR/altman-syslog.stderr.log
    ;;

  stop)
    PID=$(head -1 $PIDFILE)
    if [ ! -z $PID ] && pid_exists $PID; then
      kill $PID
    fi
    while [ -e /proc/$PID ]; do sleep 0.1; done
    rm -f $PIDFILE
    ;;

  *)
  echo "Usage: ctl {start|stop|console}" ;;
esac
exit 0
